### ISSUE TITLE
[html5_and_css3] Conclusion (29)

### ISSUE THREAD

**Issue by AlexNimoy** [codenamecrud/curriculum#109]
[html5_and_css3] conclusion (29)

Оригинал:
https://github.com/TheOdinProject/curriculum/raw/master/html_css/conclusion.md
Необходимое название файла и расположение: html5_and_css3/29_conclusion.md

**Comment by gneginskiy** [comment]
запушил  [#143](http://github.com/codenamecrud/curriculum/pull/143)

**Comment by Freika** [comment]
Где? Ставь ссылку на пулл реквест, иначе приходится искать, что к чему относится?

**Comment by gneginskiy** [comment]
[#143](http://github.com/codenamecrud/curriculum/pull/143)

**Comment by gneginskiy** [comment]
merged, можно сносить)
