### ISSUE TITLE
[Javascript] How This Course Will Work (1)

### ISSUE THREAD

**Issue by AlexNimoy** [codenamecrud/curriculum#110]
Оригинал:
https://github.com/TheOdinProject/curriculum/raw/master/javascript/introduction.md
Необходимое название файла и расположение: javascript/01_introduction.md

**Comment by Freika** [comment]
Нужно делать префикс для первых текстов, то есть не 1_name, a 01_name

**Comment by AlexNimoy** [comment]
Готово

**Comment by Freika** [comment]
#180
