### ISSUE TITLE
[Javascript] Using jQuery UI to Build Widgets (9)

### ISSUE THREAD

**Issue by AlexNimoy** [codenamecrud/curriculum#118]
Оригинал:
https://github.com/TheOdinProject/curriculum/raw/master/javascript/project_events_effects.md
Необходимое название файла и расположение: javascript/09_project_events_effects.md

**Comment by AlexKhd** [comment]
Тут путаница, 09 файл так и называется - widgets.

**Comment by Freika** [comment]
#186
