### ISSUE TITLE
[Javascript] Scope and Closures (12)

### ISSUE THREAD

**Issue by AlexNimoy** [codenamecrud/curriculum#121]
Оригинал:
https://github.com/TheOdinProject/curriculum/raw/master/javascript/scope_closures.md
Необходимое название файла и расположение: javascript/12_scope_closures.md

**Comment by Villarou** [comment]
По-моему там очепятка и должно быть что-то вроде "Почему нехорошо изменять или ссылаться на переменные вне вашей области?"
