### ISSUE TITLE
[Javascript] Loading Javascript in the Browser (17)

### ISSUE THREAD

**Issue by AlexNimoy** [codenamecrud/curriculum#126]
Оригинал:
https://github.com/TheOdinProject/curriculum/raw/master/javascript/js_to_browser.md
Необходимое название файла и расположение: javascript/17_js_to_browser.md

**Comment by Villarou** [comment]
Переведу

**Comment by Villarou** [comment]
https://github.com/codenamecrud/curriculum/pull/193

Есть сомнения в переводе фразы:

```
A very brief look back into the idea that browser loading matters (maybe).
```

Если не понравится мой - предлагайте варианты.
