### ISSUE TITLE
Conclusion (38)

### ISSUE THREAD

**Issue by Freika** [codenamecrud/curriculum#169]
Оригинал:
https://github.com/TheOdinProject/curriculum/blob/master/javascript/conclusion.md
Необходимое название файла и расположение: javascript/38_conclusion.md

**Comment by gneginskiy** [comment]
Будет готово до 22.09)

**Comment by gneginskiy** [comment]
Переведу, как появится чуть больше времени, сейчас меняю работу.

**Comment by gneginskiy** [comment]
немного разобрал свои дела, перевод в прогрессе)

**Comment by Freika** [comment]
@gneginskiy все еще никак? :)
