### ISSUE TITLE
[RoR] Сonclusion (33)

### ISSUE THREAD

**Issue by AlexNimoy** [codenamecrud/curriculum#93]
Оригинал:  
https://raw.githubusercontent.com/TheOdinProject/curriculum/master/rails/conclusion.md

Необходимое название файла и расположение: rails/33_conclusion.md

**Comment by gneginskiy** [comment]
in progress)
Чем заменить ссылки на их google-plus/meetup.com ?

**Comment by Freika** [comment]
Можно поставить ссылки на http://moscow-rb.org, группу https://groups.google.com/forum/#!forum/ror2ru и форум onrails.club

**Comment by gneginskiy** [comment]
готово, нужен взгляд со стороны)
[#173](http://github.com/codenamecrud/curriculum/pull/173)

**Comment by gneginskiy** [comment]
починил ссылки)
