### ISSUE TITLE
[html5_and_css3] tables in html (7)

### ISSUE THREAD

**Issue by AlexNimoy** [codenamecrud/curriculum#94]
Оригинал: 
https://raw.githubusercontent.com/TheOdinProject/curriculum/master/html_css/tables.md

Необходимое название файла и расположение: html5_and_css3/07_tables.md

**Comment by Mirnais** [comment]
В трелло эту статью забрал Greg Neginskiy

**Comment by gneginskiy** [comment]
запушил.

**Comment by Freika** [comment]
Аналогично, нужно ставить ссылку #144

**Comment by gneginskiy** [comment]
ок

**Comment by gneginskiy** [comment]
merged, можно сносить)
